############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2
hasChildren = true

[[main]]
parent = "About"
name = "About Us"
url = "about/"

[[main]]
parent = "About"
name = "FAQ"
url = "about/faq/"

[[main]]
name = "Company directory"
url = "blog/"
weight = 3

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
