############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "FAQ"
url = "about/faq/"
weight = 3

[[main]]
name = "Company directory"
url = "blog/"
weight = 4
hasChildren = true

[[main]]
parent = "Company directory"
name = "Products listing"
url = "products/"
weight = 1

[[main]]
parent = "Company directory"
name = "Services listing"
url = "services/"
weight = 2

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
